### ISSUE TITLE
Auth w/private key fails in 0.1.186

### ISSUE THREAD

**Issue by gino-m** [google/earthengine-api#103]
Ran into the same issue as @m-mohr, echoing here to track.

```
c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:14528
  var jwtClient = new googleapis.auth.JWT(privateKey.client_email, null, privateKey.private_key, scopes, null);
                                      ^

TypeError: Cannot read property 'JWT' of undefined
    at Object.ee.data.authenticateViaPrivateKey (c:\Dev\openeo-earthengine-driver\node_modules\@google\earthengine\build\main.js:14528:39)
    at new Server (c:\Dev\openeo-earthengine-driver\server.js:47:11)
    at Object.<anonymous> (c:\Dev\openeo-earthengine-driver\server.js:239:17)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
```

**Comment by donmccurdy** [comment]
Thanks – will get this fixed soon!

**Comment by gino-m** [comment]
Thanks! Note that the current temporary workaround is to downgrade:
```
npm install --save @google/earthengine@0.1.185
```

Use `--save-dev` instead if you're using the API as a dev dependency (e.g., for tests only).
