### ISSUE TITLE
Trying to get the array compute and receiving ENAMETOOLONG

### ISSUE THREAD

**Issue by ashu6397** [google/earthengine-api#135]
Error: spawn ENAMETOOLONG
    at ChildProcess.spawn (internal/child_process.js:394:11)
    at spawn (child_process.js:540:9)
    at exports.XMLHttpRequest.send (C:\Users\user\Documents\Dev\local-earth-engine-app\node_modules\xmlhttprequest\lib\XMLHttpRequest.js:503:22)
    at Object.module$contents$ee$apiclient_apiclient.send (C:\Users\user\Documents\Dev\local-earth-engine-app\node_modules\@google\earthengine\build\main.js:15672:13)
    at module$contents$ee$apiclient_EERequestService.send (C:\Users\user\Documents\Dev\local-earth-engine-app\node_modules\@google\earthengine\build\main.js:15453:54)
    at module$exports$eeapiclient$promise_api_client.PromiseApiClient.$request (C:\Users\user\Documents\Dev\local-earth-engine-app\node_modules\@google\earthengine\build\main.js:7060:69)
    at module$exports$eeapiclient$ee_api_client.ProjectsValueApiClientImpl.compute (C:\Users\user\Documents\Dev\local-earth-engine-app\node_modules\@google\earthengine\build\main.js:11697:26)
    at Object.ee.data.computeValue (C:\Users\user\Documents\Dev\local-earth-engine-app\node_modules\@google\earthengine\build\main.js:20617:37)
    at ee.List.ee.ComputedObject.getInfo (C:\Users\user\Documents\Dev\local-earth-engine-app\node_modules\@google\earthengine\build\main.js:21296:18)
    at Object.series (C:\Users\user\Documents\Dev\local-earth-engine-app\chart_series_data.js:137:36)e Earth Engine documentation for details on how to browse and submit issues to Issue Tracker.

**Comment by tylere** [comment]
In order to be more responsive to bug reports and feature requests, we are transitioning from using GitHub Issues to Google Issue Tracker, which better integrates with the Earth Engine team's software development workflow. Please see the [Get Help](https://developers.google.com/earth-engine/help) page of the Earth Engine documentation for details on how to browse and submit issues to Issue Tracker.
