### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Maranhao6456** [google/earthengine-api#137]
I am not able to complete the activation of GEE in QGIS. It is showing the following error:
ssl.SSLError: (SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1045)'),) 

I also tried to run the function ".\earthengine ls" and returned this:

PS C:\Users\mrmaranhao\appdata\roaming\python\python37\scripts> .\earthengine ls
Running command using Cloud API.  Set --no-use_cloud_api to go back to using the API

Traceback (most recent call last):
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\eecli.py", line 91, in main
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\program files\python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "c:\program files\python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "c:\program files\python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)
  File "c:\program files\python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "c:\program files\python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "c:\program files\python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mrmaranhao\appdata\roaming\python\python37\scripts\earthengine.exe\__main__.py", line 7, in <module>
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\eecli.py", line 94, in main
    _run_command()
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\eecli.py", line 81, in _run_command
    dispatcher.run(args, config)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\commands.py", line 349, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\commands.py", line 808, in run
    config.ee_init()
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\utils.py", line 137, in ee_init
    project=self._get_project())
ssl.SSLError: (SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)'),)
PS C:\Users\mrmaranhao\appdata\roaming\python\python37\scripts>

could someone help?

**Comment by Maranhao6456** [comment]
follows the complete return:

PS C:\Users\mrmaranhao\appdata\roaming\python\python37\scripts> .\earthengine ls
Running command using Cloud API.  Set --no-use_cloud_api to go back to using the API

Traceback (most recent call last):
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\eecli.py", line 91, in main
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\program files\python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "c:\program files\python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "c:\program files\python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\httplib2shim\__init__.py", line 148, in _conn_request
    decode_content=decode)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\request.py", line 80, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\request.py", line 171, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\util\retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 370, in connect
    ssl_context=context,
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\urllib3\util\ssl_.py", line 377, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "c:\program files\python37\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "c:\program files\python37\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "c:\program files\python37\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mrmaranhao\appdata\roaming\python\python37\scripts\earthengine.exe\__main__.py", line 7, in <module>
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\eecli.py", line 94, in main
    _run_command()
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\eecli.py", line 81, in _run_command
    dispatcher.run(args, config)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\commands.py", line 349, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\commands.py", line 808, in run
    config.ee_init()
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\cli\utils.py", line 137, in ee_init
    project=self._get_project())

  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\__init__.py", line 123, in Initialize
    http_transport=http_transport)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\data.py", line 210, in initialize
    _install_cloud_api_resource()
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\data.py", line 287, in _install_cloud_api_resource
    http_transport=_http_transport)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\ee\_cloud_api_utils.py", line 149, in build_cloud_resource
    model=alt_model)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\googleapiclient\discovery.py", line 246, in build
    requested_url, discovery_http, cache_discovery, cache, developerKey
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\googleapiclient\discovery.py", line 305, in _retrieve_discovery_doc
    resp, content = http.request(actual_url)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\google_auth_httplib2.py", line 190, in request
    self._request, method, uri, request_headers)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\google\auth\credentials.py", line 124, in before_request
    self.refresh(request)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\google\oauth2\credentials.py", line 210, in refresh
    self._scopes,
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\google\oauth2\_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\google\oauth2\_client.py", line 105, in _token_endpoint_request
    response = request(method="POST", url=token_uri, headers=headers, body=body)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\google_auth_httplib2.py", line 117, in __call__
    url, method=method, body=body, headers=headers, **kwargs)
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\httplib2\__init__.py", line 1994, in request
    cachekey,
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\httplib2\__init__.py", line 1651, in _request
    conn, request_uri, method, body, headers
  File "C:\Users\mrmaranhao\AppData\Roaming\Python\Python37\site-packages\httplib2shim\__init__.py", line 154, in _conn_request
    raise _map_exception(e)
ssl.SSLError: (SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)'),)
PS C:\Users\mrmaranhao\appdata\roaming\python\python37\scripts>

**Comment by caio-valente14** [comment]
@Maranhao6456 ,

Hi!

I'm having the same problem you posted!

Did you succeed solving that problem?

If so, can you help me out here?

Thanks a lot!

PS: Maybe we are from the same country (Brazil), so if you rather speeking portuguese it's fine.

**Comment by Maranhao6456** [comment]
Olá Caio!!

Sim, consegui resolver mas não foi fácil. Criei um doc com um passo a passo que coloco em anexo. Veja se te ajuda. Por aqui funcionou bem.

[EE_no_QGIS_vMM.docx](https://github.com/google/earthengine-api/files/5965797/EE_no_QGIS_vMM.docx)

**Comment by Maranhao6456** [comment]
@caio-valente14 

O passo a passo que eu postei te ajudou a resolver o problema?

att,

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
