### ISSUE TITLE
Python "SyntaxError: invalid syntax" when writting "ee.Authenticate()" in console

### ISSUE THREAD

**Issue by MarieSav** [google/earthengine-api#155]
Hello, I am not sure to be in the right spot for this post ... I just want to signal an issue I have when trying to use Google Earth Engine in QGIS.
In the Python console I do:
`import ee`
then
`ee.Authenticate()`
which give me
"To authorize access needed by Earth Engine, open the following URL in a web browser and follow the instructions. If the web browser does not start automatically, please manually browse the URL below.

    https://accounts.google.com/o/oauth2/auth?client_id=517222506229-vsmmajv00ul0bs7p89v5m89qs8e59.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fearthengine+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdevstorage.full_control&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&code_challenge=_JqlSXPDjncLZ4w30PMM6Lx8JC0rtZwIe6jvJcdk&code_challenge_method=S256

The authorization workflow will generate a code, which you should paste in the box below. 
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\Users\Marie\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\__init__.py", line 86, in Authenticate
    oauth.authenticate(authorization_code, quiet, code_verifier)
  File "C:\Users\Marie\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\oauth.py", line 233, in authenticate
    _obtain_and_write_token(None, code_verifier)  # Will prompt for auth_code.
  File "C:\Users\Marie\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows\ee\oauth.py", line 137, in _obtain_and_write_token
    auth_code = input('Enter verification code: ')
RuntimeError: input(): lost sys.stdin"

It also open an authentification windows, and give me a code, but when I paste it, I get:
"4/1AY0e-g7n0rxi98zQSYuCh16nuhgkA9nw-k1lireZwHDSL1PxNhFJ3-8BflE
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\codeop.py", line 168, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\codeop.py", line 99, in _maybe_compile
    raise err1
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\codeop.py", line 87, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\codeop.py", line 133, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<input>", line 1
    4/1AY0e-g7n0rxi98YuCh16nuhgkA9nw-k1lireZwHDSL1PxNhFJ3-8BflE
          ^
SyntaxError: invalid syntax"

Can someone give me some advices ? Thank you, have a good day :)

**Comment by tylere** [comment]
The error trace indicates this is occurring in the QGIS plugin. I would suggest filling an issue in the QGIS Earth Engine Plugin repository:
https://github.com/gee-community/qgis-earthengine-plugin/issues
