### ISSUE TITLE
Error with newest version : UnknownApiNameOrVersion: name: earthengine version: v1alpha

### ISSUE THREAD

**Issue by herrtunante** [google/earthengine-api#160]
Hello,

Trying to run a script with the newest version of the Python API (2.0.2) was giving me this error.

**googleapiclient.errors.UnknownApiNameOrVersion: name: earthengine  version: v1alpha**

After downgrading to version 1.12.8 my script worked fine!

Here more info : https://stackoverflow.com/questions/66498647/google-earth-engine-python-error-on-initialize-googleapiclient-errors-unknownap/66596460#66596460

**I use Python 3.8.8**

Here full log:

```
Traceback (most recent call last):
  File "C:\opt\Python3\Scripts\earthengine-script.py", line 33, in <module>
    sys.exit(load_entry_point('earthengine-api==0.1.255', 'console_scripts', 'earthengine')())
  File "c:\opt\python3\lib\site-packages\ee\cli\eecli.py", line 84, in main
    _run_command()
  File "c:\opt\python3\lib\site-packages\ee\cli\eecli.py", line 63, in _run_command
    dispatcher.run(args, config)
  File "c:\opt\python3\lib\site-packages\ee\cli\commands.py", line 353, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "c:\opt\python3\lib\site-packages\ee\cli\commands.py", line 353, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "c:\opt\python3\lib\site-packages\ee\cli\commands.py", line 1234, in run
    config.ee_init()
  File "c:\opt\python3\lib\site-packages\ee\cli\utils.py", line 133, in ee_init
    ee.Initialize(
  File "c:\opt\python3\lib\site-packages\ee\__init__.py", line 116, in Initialize
    data.initialize(
  File "c:\opt\python3\lib\site-packages\ee\data.py", line 199, in initialize
    _install_cloud_api_resource()
  File "c:\opt\python3\lib\site-packages\ee\data.py", line 266, in _install_cloud_api_resource
    _cloud_api_resource = _cloud_api_utils.build_cloud_resource(
  File "c:\opt\python3\lib\site-packages\ee\_cloud_api_utils.py", line 143, in build_cloud_resource
    resource = discovery.build(
  File "c:\opt\python3\lib\site-packages\googleapiclient\_helpers.py", line 134,
 in positional_wrapper
    return wrapped(*args, **kwargs)
  File "c:\opt\python3\lib\site-packages\googleapiclient\discovery.py", line 273
, in build
    content = _retrieve_discovery_doc(
  File "c:\opt\python3\lib\site-packages\googleapiclient\discovery.py", line 387
, in _retrieve_discovery_doc
    raise UnknownApiNameOrVersion("name: %s  version: %s" % (serviceName, version))
googleapiclient.errors.UnknownApiNameOrVersion: name: earthengine  version: v1alpha

```

**Comment by simonff** [comment]
Conda doesn't have the new version yet. We are working on it.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
