### ISSUE TITLE
Installation with python 3.6: error network unreachable

### ISSUE THREAD

**Issue by defelix** [google/earthengine-api#36]
Following the info about the installation of Google Earth engine Python API on Linux I tried to install for python 3.6.
After having installed everything and having set up the authentication credentials, I have tested the installation using:
import ee
ee.Initialize()
after last command I got the error Network is unreachable.
I followed the same steps with python 2.7, but it is working.
Please let me know if there is something I can do.
Below you can find the full message:

(geospatial_test) bash-4.2$ python -c "import ee; ee.Initialize()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/__init__.py", line 93, in Initialize
    ApiFunction.initialize()
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/apifunction.py", line 151, in initialize
    signatures = data.getAlgorithms()
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/data.py", line 423, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/data.py", line 789, in send_
    response, content = send_with_backoff()
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/data.py", line 779, in send_with_backoff
    headers=headers)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/oauth2client-4.1.2-py3.6.egg/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/oauth2client-4.1.2-py3.6.egg/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/oauth2client-4.1.2-py3.6.egg/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/oauth2client-4.1.2-py3.6.egg/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/httplib2-0.10.3-py3.6.egg/httplib2/__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/httplib2-0.10.3-py3.6.egg/httplib2/__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/httplib2-0.10.3-py3.6.egg/httplib2/__init__.py", line 995, in _conn_request
    conn.connect()
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
(geospatial_test) bash-4.2$ python -c "from oauth2client import crypt"
(geospatial_test) bash-4.2$ python -c "import ee; ee.Initialize()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/__init__.py", line 93, in Initialize
    ApiFunction.initialize()
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/apifunction.py", line 151, in initialize
    signatures = data.getAlgorithms()
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/data.py", line 423, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/data.py", line 789, in send_
    response, content = send_with_backoff()
  File "/home/v-user/Downloads/earthengine-api-0.1.134/python/ee/data.py", line 779, in send_with_backoff
    headers=headers)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/oauth2client-4.1.2-py3.6.egg/oauth2client/transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/oauth2client-4.1.2-py3.6.egg/oauth2client/client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/oauth2client-4.1.2-py3.6.egg/oauth2client/client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/oauth2client-4.1.2-py3.6.egg/oauth2client/transport.py", line 282, in request
    connection_type=connection_type)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/httplib2-0.10.3-py3.6.egg/httplib2/__init__.py", line 1322, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/httplib2-0.10.3-py3.6.egg/httplib2/__init__.py", line 1072, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/site-packages/httplib2-0.10.3-py3.6.egg/httplib2/__init__.py", line 995, in _conn_request
    conn.connect()
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/http/client.py", line 1392, in connect
    super().connect()
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/home/v-user/anaconda3/envs/geospatial_test/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

**Comment by tylere** [comment]
Given that you are using anaconda, could you try the following conda-based installation path for Python 3.6?

```
$ conda create --channel conda-forge --name test-conda-forge-py36 python=3.6 earthengine-api
$ source activate test-conda-forge-py36
(test-conda-forge-py36) $ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ee
>>> ee.Initialize()
>>> print(ee.Image('USGS/SRTMGL1_003').getThumbUrl())
https://earthengine.googleapis.com/api/thumb?thumbid=d1115de116c5ba26680fca00c4ffd7aa&token=e3eb048ddef2a82d2d38fcbc6e82ea5c
>>>
```

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
