### ISSUE TITLE
HTTP 403

### ISSUE THREAD

**Issue by ali1100** [google/earthengine-api#52]
Hi
I installed google earth engine python API by the following Steps:
https://developers.google.com/earth-engine/python_install_manua l
I created the credential file based on the instructions. but after ee.Initialize() I get this error:
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2018.1.1\helpers\pydev\pydev_run_in_console.py", line 52, in run_file
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:/Users/Kafka/PycharmProjects/untitled/earth.py", line 2, in <module>
    ee.Initialize()
  File "C:\Anaconda2\lib\site-packages\earthengine_api-0.1.141-py2.7.egg\ee\__init__.py", line 93, in Initialize
    ApiFunction.initialize()
  File "C:\Anaconda2\lib\site-packages\earthengine_api-0.1.141-py2.7.egg\ee\apifunction.py", line 151, in initialize
    signatures = data.getAlgorithms()
  File "C:\Anaconda2\lib\site-packages\earthengine_api-0.1.141-py2.7.egg\ee\data.py", line 426, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Anaconda2\lib\site-packages\earthengine_api-0.1.141-py2.7.egg\ee\data.py", line 838, in send_
    response.status)
EEException: Server returned HTTP code: 403
 is it possible to fix this?

**Comment by rban123** [comment]
Please, share how you resolved this issue for people who may also encounter this issue in the future, such as myself

**Comment by hanane-tr** [comment]
Hello @ali1100, I also have the same issue with the authentification, can you please post the solution, it's gonna bee useful for the others too, thanks in advance.
