### ISSUE TITLE
Installation on Windows, oauth2client

### ISSUE THREAD

**Issue by gena** [google/earthengine-api#53]
1. I was doing a clean install of Anaconda on Windows and noticed some installation problems. I know I can probably use conda install, but pip should work as well if the package is on pypi?

Windows 10, Anaconda 5.2.0 clean install

```
> pip install earthengine-api   this install fine, no errors

>earthengine --help
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\earthengine.EXE\__main__.py", line 5, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\ee\__init__.py", line 22, in <module>
    from ._helpers import _GetPersistentCredentials
  File "c:\programdata\anaconda3\lib\site-packages\ee\_helpers.py", line 20, in <module>
    import oauth2client.client
ModuleNotFoundError: No module named 'oauth2client'

> pip install oauth2client       solves the error

```

Is setup.py missing oauth2client in install_requires=[...]?

2. Small errors in package METADATA: License: UNKNOWN, Platform: UNKNOWN

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
