### ISSUE TITLE
WinError 10060 -httplib2 raise socket_err -during ee.Initialize() when installing the earthengine-api

### ISSUE THREAD

**Issue by gracie2017** [google/earthengine-api#58]
Hi,

I tried to install the earth engine following exactly the steps here:
 https://developers.google.com/earth-engine/python_install

Used python versions:
(base) C:\Users\asus>python --version
Python 3.6.5 :: Anaconda, Inc.

Not sure whether it is due to openssl?
(base) C:\Users\asus>openssl version
WARNING: can't open config file: /usr/local/ssl/openssl.cnf
OpenSSL 1.0.2o  27 Mar 2018

Error occured when  ee.Initialize(), wanting to initialize the connection.
Error Messages are as below:
(base) C:\Users\asus>python -c "import ee; ee.Initialize()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\asus\anaconda\lib\site-packages\earthengine_api-0.1.148-py3.6.egg\ee\__init__.py", line 100, in Initialize
    ApiFunction.initialize()
  File "C:\Users\asus\anaconda\lib\site-packages\earthengine_api-0.1.148-py3.6.egg\ee\apifunction.py", line 152, in initialize
    signatures = data.getAlgorithms()
  File "C:\Users\asus\anaconda\lib\site-packages\earthengine_api-0.1.148-py3.6.egg\ee\data.py", line 449, in getAlgorithms
    return send_('/algorithms', {}, 'GET')
  File "C:\Users\asus\anaconda\lib\site-packages\earthengine_api-0.1.148-py3.6.egg\ee\data.py", line 827, in send_
    response, content = send_with_backoff()
  File "C:\Users\asus\anaconda\lib\site-packages\earthengine_api-0.1.148-py3.6.egg\ee\data.py", line 818, in send_with_backoff
    url, method=opt_method, body=payload, headers=headers)
  File "C:\Users\asus\anaconda\lib\site-packages\oauth2client\transport.py", line 159, in new_request
    credentials._refresh(orig_request_method)
  File "C:\Users\asus\anaconda\lib\site-packages\oauth2client\client.py", line 749, in _refresh
    self._do_refresh_request(http)
  File "C:\Users\asus\anaconda\lib\site-packages\oauth2client\client.py", line 780, in _do_refresh_request
    body=body, headers=headers)
  File "C:\Users\asus\anaconda\lib\site-packages\oauth2client\transport.py", line 282, in request
    connection_type=connection_type)
  File "C:\Users\asus\anaconda\lib\site-packages\httplib2\__init__.py", line 1514, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "C:\Users\asus\anaconda\lib\site-packages\httplib2\__init__.py", line 1264, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "C:\Users\asus\anaconda\lib\site-packages\httplib2\__init__.py", line 1187, in _conn_request
    conn.connect()
  **File "C:\Users\asus\anaconda\lib\site-packages\httplib2\__init__.py", line 1050, in connect
    raise socket_err**
  File "C:\Users\asus\anaconda\lib\site-packages\httplib2\__init__.py", line 1011, in connect
    sock.connect((self.host, self.port))
**TimeoutError: [WinError 10060] 
"The connection attempt failed because the connected party did not respond correctly after a period of time or the connected host did not respond."**

**Comment by calebjuma27** [comment]
hi
try to trouble shoot your network's "incoming connections". i was experiencing something similar and doing that solved the issue
