### ISSUE TITLE
python calls getInfo function and  return exception

### ISSUE THREAD

**Issue by NiceSugar** [google/earthengine-api#89]
when I use the python to call the image object "getInfo()" function,it will return "ee.ee_exception.EEException: An internal server error has occurred (c48124edb9838eccce4c1b2f402a8d34".Does anyone knows the reason?How to solve this problem?

**Comment by asimrajan** [comment]
Were you able to solve this error?
I got the same error, here is the complete traceback for it:

`Traceback (most recent call last):
  File "/usr/lib/python3.6/dist-packages/ee/data.py", line 345, in _execute_cloud_call
    return call.execute(num_retries=num_retries)
  File "/usr/lib/python3.6/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/lib/python3.6/dist-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://earthengine.googleapis.com/v1alpha/projects/earthengine-legacy/value:compute?prettyPrint=false&alt=json returned "An internal error has occurred">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-3-4957a2ed6a6e>", line 81, in get_wraap
    l2l = np.array((ee.Array(img.get("VV1_Last_2_last")).getInfo()))
  File "/usr/lib/python3.6/dist-packages/ee/computedobject.py", line 95, in getInfo
    return data.computeValue(self)
  File "/usr/lib/python3.6/dist-packages/ee/data.py", line 710, in computeValue
    prettyPrint=False))['result']
  File "/usr/lib/python3.6/dist-packages/ee/data.py", line 347, in _execute_cloud_call
    raise _translate_cloud_exception(e)
ee.ee_exception.EEException: An internal error has occurred`

**Comment by Jiang2019Code** [comment]
Update all your GEE reference lib.I solved this problem.Check your code the filter data code.

**Comment by schwehr** [comment]
Closing. If you are still having trouble, please follow the instructions here: https://developers.google.com/earth-engine/help
