### ISSUE TITLE
Trying to cancel tasks using command line tool returns error

### ISSUE THREAD

**Issue by cgmorton** [google/earthengine-api#95]
With version 0.1.180 of the API, if I try to cancel a known running task (or all tasks) using the command line tool:
```
earthengine task cancel H4Q4ZD7XX4OIT6T3DDSSDKWS
```
I get the following traceback:
```
Canceling task "H4Q4ZD7XX4OIT6T3DDSSDKWS"
Traceback (most recent call last):
  File "C:\Miniconda3\envs\python3\Scripts\earthengine-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Miniconda3\envs\python3\lib\site-packages\ee\cli\eecli.py", line 72, in main
    dispatcher.run(args, config)
  File "C:\Miniconda3\envs\python3\lib\site-packages\ee\cli\commands.py", line 302, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "C:\Miniconda3\envs\python3\lib\site-packages\ee\cli\commands.py", line 302, in run
    self.command_dict[vars(args)[self.dest]].run(args, config)
  File "C:\Miniconda3\envs\python3\lib\site-packages\ee\cli\commands.py", line 938, in run
    ee.data.cancelTask(task_id)
  File "C:\Miniconda3\envs\python3\lib\site-packages\ee\deprecation.py", line 32, in Wrapper
    return func(*args, **kwargs)
  File "C:\Miniconda3\envs\python3\lib\site-packages\ee\data.py", line 1073, in cancelTask
    cancelOperation(_cloud_api_utils.convert_task_id_to_operation_name(taskId))
  File "C:\Miniconda3\envs\python3\lib\site-packages\ee\data.py", line 1078, in cancelOperation
    _execute_cloud_call(_cloud_api_resource.operations().cancel(
AttributeError: 'Resource' object has no attribute 'operations'
```

The same command works if I roll back to 0.1.175 (the last version available through conda).

**Comment by cgmorton** [comment]
Closing this since cancelling tasks has worked since at least 0.1.204
